# Generated by Django 4.2.6 on 2023-10-21 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mealApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
