# Generated by Django 4.2.5 on 2023-09-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insulineDozes', '0002_doze_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doze',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='doze',
            name='timestamp',
            field=models.DateTimeField(unique=True),
        ),
    ]
