# Generated by Django 4.2.6 on 2023-10-21 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insulineDozes', '0003_alter_doze_description_alter_doze_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doze',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
