# Generated by Django 4.2.5 on 2023-09-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doze',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
