# Generated by Django 4.2.5 on 2023-09-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='GlucoseLevel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField(unique=True)),
                ('unit', models.CharField(choices=[('1', 'mg/dL'), ('2', 'mmol/l')], default='1', max_length=2)),
            ],
        ),
    ]
