# Generated by Django 4.2.6 on 2023-10-21 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glucoseLevelApp', '0002_glucoselevel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucoselevel',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
